# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Gustavo Siqueira's blog"
description: > # this means to ignore newlines until "email:"
   

email: gosiqueira@dcc.ufmg.br
#blog logo
logo: "https://avatars3.githubusercontent.com/u/11512513?v=4"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/layout-background"

name: 'Gustavo Siqueira'
author: 'Gustavo Siqueira'
author_image: "https://avatars3.githubusercontent.com/u/11512513?v=4"

paginate:	5

url: "http://gosiqueira.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: 

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

google_analytics: UA-157615100-2

# social icons and sharing options
social:
  - icon:	linkedin
    url:	https://www.linkedin.com/in/gustavo-siqueira-5a6282b9/
    desc: Conect with me on LinkedIn
    share_url: 
    share_title: 
    share_link: 

  - icon:	github
    url:	https://github.com/gosiqueira
    desc:	Follow me on GitHub.
    share_url:
    share_title:
    share_link:

